apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-service-tcs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Neeraj-2806/itom.git
    targetRevision: main
    path: helm/tenant
    helm:
      releaseName: tenant-service
      values: |
        replicaCount: 1

        nameOverride: "tenant-service"
        fullnameOverride: ""

        image:
          repository: neeraj2806/eight-tenant-itom
          tag: "v1"
          pullPolicy: IfNotPresent

        service:
          type: ClusterIP
          port: 5003

        env:
          PORT: "5003"
          REDIS_URL: "redis://redis-tcs:6379"

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        serviceAccount:
          create: true
          automount: false
          name: ""

        strategy:
          rollingUpdate:
            maxUnavailable: 0
            maxSurge: 1

        livenessProbe:
          path: /health
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          path: /health
          initialDelaySeconds: 10
          periodSeconds: 5

        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 5
          targetCPUUtilizationPercentage: 70
          targetMemoryUtilizationPercentage: 80
  destination:
    server: https://kubernetes.default.svc
    namespace: tenant-tcs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
