apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-infosys
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Neeraj-2806/itom.git
    targetRevision: main
    path: gitops/tenants/infosys
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
