apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "asset-service.fullname" . }}
  labels:
    {{- include "asset-service.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}

  selector:
    matchLabels:
      {{- include "asset-service.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "asset-service.selectorLabels" . | nindent 8 }}

    spec:
      serviceAccountName: {{ include "asset-service.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}

      containers:
        - name: {{ include "asset-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}

          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ include "asset-service.fullname" $ }}-configmap
                  key: {{ $key }}
            {{- end }}

          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          {{- end }}

          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
